# For PMM-6482 new documentation structure
site_name: Percona Monitoring and Management Documentation
site_description: Percona Monitoring and Management Documentation
site_author: Percona LLC
copyright: Percona LLC, &#169; 2020
use_directory_urls: true
site_dir: site_pdf

theme:
    name: material

markdown_extensions:
    - toc:
        baselevel: 1
        toc_depth: "2-3"
    - admonition
    - def_list
    - smarty:
        smart_angled_quotes: True
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed
    - pymdownx.tilde
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: false


extra:
    release: &release '2.11.1'
    version: '2.11'
    major: '2.x' # Publish url suffix (percona.com/doc/percona-monitoring-and-management/2.x)
    quickstart: 'https://www.percona.com/software/pmm/quickstart'

plugins:
    - search
    - macros
    - with-pdf:
        output_path: '_pdf/PerconaMonitoringAndManagement-2.11.1.pdf'
        cover_title: 'Documentation'
        cover_subtitle: *release
        author: 'Percona Technical Documentation Team'
        cover_logo: docs/_images/PMM_Logo.svg
        debug_html: false

nav:
    - Welcome: index.md
    - Setting up:
        - setting-up/index.md
        - Server:
            - setting-up/server/index.md
            - setting-up/server/docker.md
            - setting-up/server/virtual-appliance.md
            - setting-up/server/aws.md
        - Client:
            - setting-up/client/index.md
            - setting-up/client/mysql.md
            - setting-up/client/percona-server.md
            - setting-up/client/mongodb.md
            - setting-up/client/postgresql.md
            - setting-up/client/proxysql.md
            - setting-up/client/aws.md
            - setting-up/client/linux.md
            - setting-up/client/external.md
    - Using:
        - using/index.md
        - using/interface.md
        - using/query-analytics.md
        - Percona Platform:
            - using/platform/index.md
            - using/platform/dbaas.md
            - using/platform/security-threat-tool.md
    - How to:
        - how-to/index.md
        - how-to/upgrade.md
        - how-to/secure.md
        - how-to/optimize.md
        - how-to/configure.md
    - Details:
        - details/index.md
        - Dashboards:
            - Insight:
                - Advanced Data Exploration: details/dashboards/dashboard-advanced-data-exploration.md
                - Home Dashboard: details/dashboards/dashboard-home.md
            - PMM:
                - PMM Inventory: details/dashboards/dashboard-inventory.md
            - OS Dashboards:
                - CPU Utilization Details: 'details/dashboards/dashboard-cpu-utilization-details.md'
                - Disk Details: 'details/dashboards/dashboard-disk-details.md'
                - Network Details: 'details/dashboards/dashboard-network-details.md'
                - Memory Details: 'details/dashboards/dashboard-memory-details.md'
                - Node Temperature Details: 'details/dashboards/dashboard-node-temperature-details.md'
                - Nodes Compare: 'details/dashboards/dashboard-nodes-compare.md'
                - Nodes Overview: 'details/dashboards/dashboard-nodes-overview.md'
                - Node Summary: 'details/dashboards/dashboard-node-summary.md'
                - NUMA Details: 'details/dashboards/dashboard-numa-details.md'
                - Processes Details: 'details/dashboards/dashboard-processes-details.md'
            - Prometheus Dashboards:
                - Prometheus: 'details/dashboards/dashboard-prometheus.md'
                - Prometheus Exporter Status: 'details/dashboards/dashboard-prometheus-exporter-status.md'
                - Prometheus Exporters Overview: 'details/dashboards/dashboard-prometheus-exporters-overview.md'
            - MySQL Dashboards:
                - MySQL Amazon Aurora Details: 'details/dashboards/dashboard-mysql-amazon-aurora-details.md'
                - MySQL Command/Handler Counters Compare: 'details/dashboards/dashboard-mysql-command-handler-counters-compare.md'
                - MySQL InnoDB Compression Details: 'details/dashboards/dashboard-mysql-innodb-compression-details.md'
                - MySQL InnoDB Details: 'details/dashboards/dashboard-mysql-innodb-details.md'
                - MySQL MyISAM/Aria Details: 'details/dashboards/dashboard-mysql-myisam-aria-details.md'
                - MySQL MyRocks Details: 'details/dashboards/dashboard-mysql-myrocks-details.md'
                - MySQL Instance Summary: 'details/dashboards/dashboard-mysql-instance-summary.md'
                - MySQL Instances Compare: 'details/dashboards/dashboard-mysql-instances-compare.md'
                - MySQL Instances Overview: 'details/dashboards/dashboard-mysql-instances-overview.md'
                - MySQL Wait Event Analyses Details: 'details/dashboards/dashboard-mysql-wait-event-analyses-details.md'
                - MySQL Performance Schema Details: 'details/dashboards/dashboard-mysql-performance-schema-details.md'
                - MySQL Query Response Time Details: 'details/dashboards/dashboard-mysql-query-response-time-details.md'
                - MySQL Replication Summary: 'details/dashboards/dashboard-mysql-replication-summary.md'
                - MySQL Group Replication Summary: 'details/dashboards/dashboard-mysql-group-replication-summary.md'
                - MySQL Table Details: 'details/dashboards/dashboard-mysql-table-details.md'
                - MySQL User Details: 'details/dashboards/dashboard-mysql-user-details.md'
                - MySQL TokuDB Details: 'details/dashboards/dashboard-mysql-tokudb-details.md'
            - MongoDB Dashboards:
                - MongoDB Cluster Summary: 'details/dashboards/dashboard-mongodb-cluster-summary.md'
                - MongoDB Instance Summary: 'details/dashboards/dashboard-mongodb-instance-summary.md'
                - MongoDB Instances Overview: 'details/dashboards/dashboard-mongodb-instances-overview.md'
                - MongoDB Instances Compare: 'details/dashboards/dashboard-mongodb-instances-compare.md'
                - MongoDB ReplSet Summary: 'details/dashboards/dashboard-mongodb-replset-summary.md'
                - MongoDB InMemory Details: 'details/dashboards/dashboard-mongodb-inmemory-details.md'
                - MongoDB MMAPv1 Details: 'details/dashboards/dashboard-mongodb-mmapv1-details.md'
                - MongoDB WiredTiger Details: 'details/dashboards/dashboard-mongodb-wiredtiger-details.md'
            - PostgreSQL Dashboards:
                - PostgreSQL Instances Overview: 'details/dashboards/dashboard-postgresql-instances-overview.md'
                - PostgreSQL Instance Summary: 'details/dashboards/dashboard-postgresql-instance-summary.md'
                - PostgreSQL Instances Compare: 'details/dashboards/dashboard-postgresql-instances-compare.md'
            - ProxySQL Dashboards:
                - ProxySQL Instance Summary: 'details/dashboards/dashboard-proxysql-instance-summary.md'
            - HA Dashboards:
                - PXC/Galera Node Summary: 'details/dashboards/dashboard-pxc-galera-node-summary.md'
                - PXC/Galera Cluster Summary: 'details/dashboards/dashboard-pxc-galera-cluster-summary.md'
                - PXC/Galera Nodes Compare: 'details/dashboards/dashboard-pxc-galera-nodes-compare.md'
        - Commands:
            - details/commands/pmm-admin.md
        - details/api.md
        - details/glossary.md
    - faq.md
    - Release Notes:
        - release-notes/2.11.1.md
        - release-notes/2.11.0.md
        - release-notes/2.10.1.md
        - release-notes/2.10.0.md
        - release-notes/2.9.1.md
        - release-notes/2.9.0.md
        - release-notes/2.8.0.md
        - release-notes/2.7.0.md
        - release-notes/2.6.1.md
        - release-notes/2.6.0.md
        - release-notes/2.5.0.md
        - release-notes/2.4.0.md
        - release-notes/2.3.0.md
        - release-notes/2.2.2.md
        - release-notes/2.2.1.md
        - release-notes/2.2.0.md
        - release-notes/2.1.0.md
        - release-notes/2.0.1.md
        - release-notes/2.0.0.md
