' Styles for PlantUML created diagrams
skinparam {
  roundcorner 20
  defaultFontName Chivo
  defaultFontSize 14
  defaultTextAlignment center
  ArrowHeadColor none
  BackgroundColor #fff
  ActivityBackgroundColor #99ccff
  activityDiamondBackgroundColor #99ccff
}
<style>
wbsDiagram {
  node {
    BackgroundColor #ff9933
'    RoundCorner 10
    Padding 5
    Margin 5
  }
}
</style>
