' Diagram showing sequence of tasks to set up Virtual Appliance
' Syntax: https://plantuml.com/activity-diagram-beta
' Icons: https://plantuml.com/openiconic
' Colour: https://plantuml.com/color
' Text: https://plantuml.com/creole

@startuml
title Running PMM Server as a virtual appliance\nTask overview\n
#application:Download;
#application:Verify;
#application:Import;
#application:Reconfigure interface;
#application:Get IP address;
#application:Log in;
#application:Change root password;
split
	#lightgrey:(Optional) Set up SSH;
kill
split again
	#lightgrey:(Optional) Set up static IP;
kill
@enduml
