' Diagram showing sequence of tasks to set up PMM Client for MySQL
' Syntax: https://plantuml.com/activity-diagram-beta
' Icons: https://plantuml.com/openiconic
' Colour: https://plantuml.com/color
' Text: https://plantuml.com/creole
@startuml "setting-up_client_mysql"
skinparam ArrowHeadColor none
skinparam roundCorner 10
skinparam legendBackgroundColor #0000
'title "Setting up PMM Client to monitor a MySQL host\nOverview\n"
legend bottom left
Legend
<#lemonchiffon>| Required |
<#lightgrey>| Optional |
endlegend

#lightgrey:1. Create PMM database account;
partition "2. Choose and configure\n     a source" {
	if (Choose a source) then (**//slow query log//**)
		:2.1. slow query log;
		:2.2. slow query log - additional;
		#lightgrey:2.3. slow query log rotation;
		#lightgrey:2.3. query response time;
		#lightgrey:2.4. tablestats;
	else (**//Performance Schema//**)
		:2.5. Performance Schema;
	endif
	#lightgrey:2.7. **//user statistics//**;
}
partition "3. Add service" {
	if () then (**3.1. User interface**)
		:PMM <&arrow-thick-right> PMM Add Instance <&arrow-thick-right>\nMySQL - Add a remote instance;
	else (**3.2. Command line**)
		if () then (**Slow query log**)
			:<code>
			pmm-admin add mysql
			--query-source=slowlog
			--size-slow-logs=N
			...
			</code>;
		else (**Performance Schema**)
			:<code>
			pmm-admin add mysql
			--query-source=perfschema
			...
			</code>;
		endif
	endif
}
#lightgrey:4. Check;
@enduml
