@startuml "PMM Components"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include resources/plantuml_styles.puml
HIDE_STEREOTYPE()
'LAYOUT_LEFT_RIGHT()


'Person_Ext(user, "User")
Boundary(customer_system1, "User system") {
    System_Ext(database, "Monitored", " ")
    Boundary(pmm_client, "PMM Client") {
        System(exporters, "exporters", "")
        System(pmm_agent, "pmm-agent", "")
        System(vmagent, "vmagent", "")
    }
}
Boundary(customer_system2, "User system") {
    Boundary(pmm_server, "PMM Server") {
        System(pmm_managed, "pmm-managed", "")
        System(query_analytics, "Query Analytics", "")
        System(victoriametrics, "VictoriaMetrics", "")
    }
}
' Layout
BiRel_R(pmm_agent, pmm_managed, " ")
' Relations
Rel(database, exporters, " ")
Rel_R(pmm_agent, database, "Query Analytics metrics")
Rel_D(exporters, vmagent, " ")
Rel_D(pmm_agent, exporters, "Runs")
Rel_R(pmm_managed, query_analytics, " ")
Rel(pmm_managed, victoriametrics, " ")
Rel_R(exporters, victoriametrics, "Pull")
Rel_U(vmagent, victoriametrics, "Push")
@enduml
