name: Test helm.md

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "docs/setting-up/server/helm.md"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: percona-platform/checkout@v2
        with:
          fetch-depth: 1

      - name: Install pandoc
        run: | 
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo apt-get install -y ./pandoc-2.18-1-amd64.deb

      - name: Copy test template
        run: cp _resources/bin/doc_test_template.sh ./docs_test_helm.sh

      - name: Get CodeBlocks and push them to test template
        run: pandoc -i docs/setting-up/server/helm.md --lua-filter _resources/bin/CodeBlock.lua -t html -o /dev/null >> docs_test_helm.sh

      - name: Start k8s cluster
        run: minikube start

      - name: Setup storage driver for snapshots
        run: | 
          minikube addons disable storage-provisioner
          kubectl delete storageclass standard
          minikube addons enable csi-hostpath-driver
          minikube addons enable volumesnapshots
          kubectl patch storageclass csi-hostpath-sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

      - name: Run helm tests
        run: ./docs_test_helm.sh

      - name: Get debug
        if: ${{ failure() }}
        run: | 
          cat ./docs_test_helm.sh
          pandoc --version
          helm version
          kubectl get pods
          kubectl describe pod --selector=app.kubernetes.io/name=pmm || true
          kubectl get events --sort-by=lastTimestamp 
          kubectl logs --all-containers --timestamps --selector=app.kubernetes.io/name=pmm || true
