name: Upload artefacts to GCS

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: percona-platform/checkout@v2
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        id: "auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_BUILD_BUCKET_KEY }}"

      - name: Upload files to GCS
        id: "upload-files"
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: "_resources"
          destination: "doc-builds/${GITHUB_REF}"
          parent: false
          gzip: true
