name: Test podman.md

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "docs/setting-up/server/podman.md"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: percona-platform/checkout@v2
        with:
          fetch-depth: 1

      - name: Install pandoc
        run: | 
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo apt-get install -y ./pandoc-2.18-1-amd64.deb

      - name: Copy test template
        run: cp _resources/bin/doc_test_template.sh ./docs_test_podman.sh

      - name: Get CodeBlocks and push them to test template
        run: pandoc -i docs/setting-up/server/podman.md --lua-filter _resources/bin/CodeBlock.lua -t html -o /dev/null >> docs_test_podman.sh

      - name: Run podman tests
        run: ./docs_test_podman.sh

      - name: Get debug
        if: ${{ failure() }}
        run: | 
          cat ./docs_test_podman.sh
          pandoc --version
          podman version
          podman ps --all || true
          systemctl status --user pmm-server || true
          podman inspect pmm-server || true
          journalctl -r || true
